# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 18:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRBPIUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('receive_message', models.BooleanField(default=True, verbose_name='receive messages')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_group', models.BooleanField(default=False, verbose_name='is group')),
            ],
            options={
                'permissions': (('can_control_RBPI_users', 'To HR department'),),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('status_name', models.PositiveSmallIntegerField(choices=[(0, 'ON_ACTIVE'), (1, 'ON_DELETED,'), (2, 'ON_MODIFY'), (3, 'ON_REPAIR')], default=0, verbose_name='status')),
                ('name_of_legal', models.CharField(max_length=40, verbose_name='Legal Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('status_name', models.PositiveSmallIntegerField(choices=[(0, 'ON_ACTIVE'), (1, 'ON_DELETED,'), (2, 'ON_MODIFY'), (3, 'ON_REPAIR')], default=0, verbose_name='status')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.BaseRBPIUser', verbose_name='from user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('user_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseRBPIUser', verbose_name='modifier user')),
            ],
            options={
                'permissions': (('can_create_messages', 'To HR department'),),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('status_name', models.PositiveSmallIntegerField(choices=[(0, 'ON_ACTIVE'), (1, 'ON_DELETED,'), (2, 'ON_MODIFY'), (3, 'ON_REPAIR')], default=0, verbose_name='status')),
                ('name', models.CharField(max_length=40, verbose_name='Office')),
                ('user_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseRBPIUser', verbose_name='modifier user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='offices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Office', verbose_name='Offices'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='user_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseRBPIUser', verbose_name='modifier user'),
        ),
        migrations.AddField(
            model_name='baserbpiuser',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LegalEntity'),
        ),
    ]
