# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 21:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baserbpiuser',
            managers=[
                ('objects_active_users', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
