# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 09:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180106_2325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='legalentity',
            managers=[
                ('objects_active_legal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='office',
            managers=[
                ('objects_active_offices', django.db.models.manager.Manager()),
            ],
        ),
    ]
