# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('status_name', models.PositiveSmallIntegerField(choices=[(0, 'ON_ACTIVE'), (1, 'ON_DELETED'), (2, 'ON_MODIFY'), (3, 'ON_REPAIR')], default=0, verbose_name='status')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active order')),
                ('first_course', models.PositiveSmallIntegerField(default=0, verbose_name='first_course')),
                ('second_course', models.PositiveSmallIntegerField(default=0, verbose_name='second_course')),
                ('salad', models.PositiveSmallIntegerField(default=0, verbose_name='salad')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.BaseRBPIUser', verbose_name='user')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Office', verbose_name='Office')),
                ('user_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BaseRBPIUser', verbose_name='modifier user')),
            ],
            options={
                'permissions': (('can_control_order', 'To HR control order'),),
            },
        ),
    ]
