# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 18:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchProvider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('receive_message', models.BooleanField(default=True, verbose_name='receive messages')),
                ('count_first_course', models.PositiveSmallIntegerField()),
                ('count_second_course', models.PositiveSmallIntegerField()),
                ('count_salad', models.PositiveSmallIntegerField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Office', verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='modified')),
                ('status_name', models.PositiveSmallIntegerField(choices=[(0, 'ON_ACTIVE'), (1, 'ON_DELETED,'), (2, 'ON_MODIFY'), (3, 'ON_REPAIR')], default=0, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active order')),
                ('first_course', models.PositiveSmallIntegerField(default=0, verbose_name='first_course')),
                ('second_course', models.PositiveSmallIntegerField(default=0, verbose_name='second_course')),
                ('salad', models.PositiveSmallIntegerField(default=0, verbose_name='salad')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Office', verbose_name='Office')),
                ('user_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseRBPIUser', verbose_name='modifier user')),
            ],
            options={
                'permissions': (('can control order', 'To HR control order'),),
            },
        ),
    ]
